name: Публикация на GitHub Pages

on:
  release:
    types: [published]   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка кода из репозитория
        uses: actions/checkout@v4  

      - name: Публикация версии в папку v<release>
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
          publish_dir: public          
          keep_files: true              
          destination_dir: ${{ github.event.release.tag_name }}  

      - name: Дублируем последнюю версию в корень
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
          destination_dir: ""  
